# global parameters
project_name: 'Data-Juicer-recipes-alpaca-cot-en'
dataset_path: '../data/raw_data/raw_data_en.jsonl'  # path to your dataset directory or file
export_path: '../data/proc_data/proc_data_en.jsonl'

np: 72  # number of subprocess to process your dataset
open_tracer: true

# process schedule
# a list of several process operators with their arguments
process:


  - clean_email_mapper:                                     # remove emails from text.
  - punctuation_normalization_mapper:                       # normalize unicode punctuations to English punctuations.
  - fix_unicode_mapper:                                     # fix unicode errors in text.
  - whitespace_normalization_mapper:

  - alphanumeric_filter: # 104636381
      tokenization: false
      min_ratio: 0.1
      max_ratio: 0.9
  - character_repetition_filter: # 104630030
      rep_len: 10
      max_ratio: 0.6
  - flagged_words_filter: # 104576967
      lang: en
      tokenization: true
      max_ratio: 0.017
  - maximum_line_length_filter: # 104575811
      min_len: 20
  - text_length_filter: # 104573711
      min_len: 20
      max_len: 10000
  - perplexity_filter:          # filter text with perplexity score out of specific range
      lang: en                                                # compute perplexity in what language
      max_ppl: 1000                                           # the max perplexity score to filter text
  - special_characters_filter:                              # filter text with special-char ratio out of specific range
      min_ratio: 0.0                                          # the min ratio of filter range
      max_ratio: 0.25
  - html_filter:

  - document_deduplicator: # 104636705
      lowercase: true
      ignore_non_character: true
  - document_simhash_deduplicator:  # 72855345
      tokenization: space
      window_size: 6
      lowercase: true
      ignore_pattern: '\p{P}'
      num_blocks: 9
      hamming_distance: 7

  - balanced_selector: